version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          PG_HOST: localhost
          PG_USER: ag_weather
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:12.8
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ag_weather_test
          POSTGRES_PASSWORD: "password"
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Get Bundler
          command: gem install bundler
      - run:
          name: Configure Bundler
          command: bundle config set --local path './vendor/bundle'
      - run:
          name: Install Dredd
          command: npm install dredd
      - restore_cache:
          keys:
            - agweather-bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
            - agweather-bundle
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
         key: agweather-bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
         paths:
           - ./vendor/bundle
      - run:
          name: Set up database
          command: bin/rails db:setup
          environment:
            DATABASE_URL: postgres://ag_weather@localhost:5432/ag_weather_test
      - run:
          name: Rspec
          command: bundle exec rspec
          environment:
            DATABASE_URL: postgres://ag_weather@localhost:5432/ag_weather_test
      - run:
          name: Run Dredd API test
          command: |
            export PATH="$(npm bin):$PATH"
            RAILS_ENV=test bundle exec rake dredd
          environment:
            DATABASE_URL: postgres://ag_weather@localhost:5432/ag_weather_test
