version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.1-node
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          RAILS_ENV: test
          RACK_ENV: test
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ag_weather_test
          POSTGRES_PASSWORD: "password"
    executor: ruby/default
    resource_class: large
    steps:
      - checkout
      - ruby/install-deps:
          key: gems-v1
      - run:
          name: Install Dredd
          command: npm install dredd --global
      - run:
          name: Install gnuplot and imagemagick
          command: |
            sudo apt update
            sudo apt -y install gnuplot-qt imagemagick-6.q16
      - run:
          name: Set up database
          command: bundle exec rails db:setup
      - run:
          name: Run specs
          command: bundle exec rspec
      - run:
          name: Run Dredd API test
          command: |
            export PATH="$(npm bin):$PATH"
            RAILS_ENV=test bundle exec rake dredd
