version: 2.1
orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3-node
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          RAILS_ENV: test
          RACK_ENV: test
          CACHE_VERSION: v2
      - image: circleci/postgres:12.8
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: ag_weather_test
          POSTGRES_PASSWORD: "password"
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Install Dredd
          command: npm install dredd
      - run:
          name: Set up database
          command: bundle exec rails db:setup
      - run:
          name: Run specs
          command: bundle exec rspec
      - run:
          name: Run Dredd API test
          command: |
            export PATH="$(npm bin):$PATH"
            RAILS_ENV=test bundle exec rake dredd
