version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          PG_HOST: localhost
          PG_USER: ag_weather
          RAILS_ENV: test
          RACK_ENV: test
      - image: circleci/postgres:12.2
        environment:
          POSTGRES_USER: ag_weather
          POSTGRES_DB: ag_weather_test
          POSTGRES_PASSWORD: "password"
    steps:
      - checkout
      - run:
          name: Update Bundler
          command: gem install bundler
      - run:
          name: Configure Bundler
          command: bundle config set --local path './vendor/bundle'
      - run:
          name: Install Dredd
          command: npm install dredd
      - restore_cache:
          keys:
            - ag-weather-bundle-v1-{{ checksum "Gemfile.lock" }}
            - ag-weather-bundle-v1-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
         key: ag-weather-bundle-v1-{{ checksum "Gemfile.lock" }}
         paths:
           - ./vendor/bundle
      - run:
          name: Set up DB
          command: bin/rails db:setup
          environment:
            DATABASE_URL: postgres://ag_weather@localhost:5432/ag_weather_test
      - run:
          name: Run Specs
          command: bundle exec rspec
          environment:
            DATABASE_URL: postgres://ag_weather@localhost:5432/ag_weather_test
      - run:
          name: Run Dredd API test
          command: |
            export PATH="$(npm bin):$PATH"
            RAILS_ENV=test bundle exec rake dredd
          environment:
            DATABASE_URL: postgres://ag_weather@localhost:5432/ag_weather_test
