default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ag_weather_development

test:
  <<: *default
  database: ag_weather_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: ag_weather_production
  username: ag_weather
  password: <%= ENV['AG_WEATHER_DATABASE_PASSWORD'] %>
